app/frontends/web_rails/config/routes.rb
Web::Application.routes.draw do

  root to: 'pages#index'

  resources :gatherings

end

app/frontends/web_rails/app/controllers/application_controller.rb
# -*- coding: UTF-8 -*-

class ApplicationController < ActionController::Base

  protect_from_forgery

  include UseCases

  rescue_from RubyPersistenceAPI::ObjectNotFound, with: :show_404

  private

  def show_404
    render(file: File.join(Rails.root, 'public', '404'), status: 404, :format => :html)
  end

end

app/frontends/web_rails/app/controllers/gatherings_controller.rb
# -*- coding: UTF-8 -*-

class GatheringsController < ApplicationController

  def index
    @rm = ListGathering.new.exec
  end

  def new
    @rm = NewGathering.new.exec
  end

  def create
    @rm = CreateGathering.new(atts: params[:gathering]).exec
    @rm.ok? ? redirect_to(gatherings_path) : render(:new)
  end

  def show
    @rm = ShowGathering.new(id: params[:id]).exec
  end

  def edit
    @rm = EditGathering.new(id: params[:id]).exec
  end

  def update
    @rm = UpdateGathering.new(id: params[:id], atts: params[:gathering]).exec
    @rm.ok? ? redirect_to(gatherings_path) : render(:edit)
  end

  def destroy
    @rm = DestroyGathering.new(id: params[:id]).exec
    redirect_to(gatherings_path)
  end

end

app/frontends/web_rails/app/controllers/pages_controller.rb
# -*- coding: UTF-8 -*-

class PagesController < ApplicationController

  def index
  end

end

app/frontends/web_rails/app/helpers/application_helper.rb
module ApplicationHelper

  # view model
  def vm
    @vm || @rm # if view model is not set fallback to response model
  end

  def errors(attribute)
    return '' unless vm.errors && !vm.errors.blank?
    content_tag( 'span', class: 'help-inline' ) do
      vm.errors[attribute].join( '; ' )
    end
  end

end

app/frontends/web_rails/app/views/gatherings/_form.html.haml
.control-group{ class: ( vm.errors ? 'error' : '' ) }
  %label.control-label{ for: 'gathering_name' }
    Name
  .controls
    %input.span5{ type: 'text', id: 'gathering_name', name: 'gathering[name]', value: vm.gathering.name }
    = errors(:name)

.control-group
  %label.control-label{ for: 'gathering_type' }
    Type
  .controls
    %input.span5{ type: 'text', id: 'gathering_type', name: 'gathering[gathering_type]', value: vm.gathering.gathering_type }
    = errors(:gathering_type)

.control-group
  %label.control-label{ for: 'gathering_description' }
    Description
  .controls
    %textarea.span5{ id: 'gathering_description', name: 'gathering[description]' }
      = vm.gathering.description
    = errors(:description)

app/frontends/web_rails/app/views/gatherings/edit.html.haml
= form_for( vm.gathering, as: 'gathering', url: gathering_path( vm.gathering ), :html => { class: 'form-horizontal' } ) do |f|

  %fieldset
    %legend
      = vm.gathering.name

    = render 'form', f: f

    .form-actions
      %button{ class: 'btn btn-primary', type: 'submit' }
        Save changes
      %button{ class: 'btn', type: 'button', onclick: 'history.go(-1)' }
        Cancel

app/frontends/web_rails/app/views/gatherings/index.html.haml
- @title = 'Known gatherings'

.gatherings
  - vm.gatherings.each do |gathering|
    .gathering.row{ style: 'padding-top: 8px; padding-bottom: 8px;' }
      .name.span4
        %h4
          = gathering.name
        = gathering.gathering_type
      .description.span6
        = gathering.description
      .options.span2
        = link_to( "show", gathering_path( gathering ) )
        = link_to( "edit", edit_gathering_path( gathering ) )
        = link_to( "delete", gathering_path( gathering ), :method => :delete )

.options{ style: 'margin-top: 16px;' }
  = link_to( "New gathering", new_gathering_path, class: 'btn' )

app/frontends/web_rails/app/views/gatherings/new.html.haml
= form_for( vm.gathering, as: 'gathering', url: gatherings_path, :html => { class: 'form-horizontal' } ) do |f|

  %fieldset
    %legend
      New Gathering

    = render 'form', f: f

    .form-actions
      %button{ class: 'btn btn-primary', type: 'submit' }
        Create
      %button{ class: 'btn', type: 'button', onclick: 'history.go(-1)' }
        Cancel

app/frontends/web_rails/app/views/gatherings/show.html.haml
- @title = vm.gathering.name

.gathering.row
  .name.span4
    %h4
      = vm.gathering.name
    = vm.gathering.gathering_type
  .description.span6
    = vm.gathering.description
  .options.span2
    = link_to( "edit", edit_gathering_path( vm.gathering ) )
    = link_to( "delete", gathering_path( vm.gathering ), :method => :delete )

.options{ style: 'margin-top: 16px;' }
  = link_to( "Back to gathering list", gatherings_path, class: 'btn' )

app/frontends/web_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= @title || 'Gatherings' %>
  </title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class='row'>
      <div class='span12'>
        <h1><%= @title %></h1>

        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/frontends/web_rails/app/views/pages/index.html.haml
- @title = 'Create and Manage your very own gatherings!'

.teaser
  %p
    Whether you love to throw or organize parties or you're dreading the prospect, Gatherings is here to help!
    We provide tools to help you create and manage a gathering with nearly limitless events and invites to your guests.

  %p
    Want to break up your party into a wine-tasting trip and a barbecue afterward?  No problem with gatherings!  
    You can manage multiple events and even break up the invites across those same events.  
    Want to invite only your closest friends to the wine trip but all your coworkers to the after-party?  Gatherings can do it!

.options
  Now, why don't you
  = link_to( 'see the sample gatherings', gatherings_path )
  or
  = link_to( 'add your own gathering now', new_gathering_path ) + '?'.html_safe